### ISSUE TITLE
c3d2Opensim

### ISSUE THREAD

**Issue by ziae0005** [jimmyDunne/c3d2OpenSim#8]
Hello

I want to run this function: c3d2Opensim
But I do not know what is the problem with the below email!
Matlab = 32 Bit
Window 7 Pack1= 64bit

Please send me the requited btk file.... I do not know what's the problem!!
h.ziaeipoor@yahoo.com
Thanks

...................................
Undefined function or variable 'btkReadAcquisition'.

Error in btk_loadc3d (line 70)
acq = btkReadAcquisition(file);

Error in c3d2Opensim (line 65)
        structData = btk_loadc3d(fullfile(pathname,filein), 10);

**Comment by jimmyDunne** [comment]
Did you download the btk Matlab binaries and put them on your Matlab path?

**Comment by ziae0005** [comment]
Yes I did but it did not work.. Please send me the required link which is quite fit to my windows 7 service pack 1 64 bit

My matlab is 2015 and 32bit
Or I may send you one of my c3d files to see and check it.... I really need your help since I worked in this converting several days but still nothing
Thank you sir

**Comment by jimmyDunne** [comment]
The btk binaries can found [here](https://code.google.com/archive/p/b-tk/downloads?page=1
). There doesn't look to be a Matlab 2015 tested version. However, I have been able to use it successfully. 

The error you are getting is due to the btk binaries not being found. If you are sure that you have them on your Matlab path, check to make sure you have admin rights to the folder that contains the files. 

There are a number of alternative packages that you can use, [here](http://simtk-confluence.stanford.edu:8080/display/OpenSim/Tools+for+Preparing+Motion+Data). Check these out if you continue to have issues.

**Comment by ziae0005** [comment]
Thank you
Which version did you use? Can you send me that version for 2015 that u checked it before ?
